import type { ToolRegistry } from './registry.js'
import type { JsonSchema } from './schema.js'
import type { ToolDefinition } from './types.js'

/**
 * **从工具定义生成参考文档**（plan §11 的 `docs/tool-reference.md` 与 `.zh-CN.md`）。
 *
 * 手写的工具文档一定会漂移：改了 schema 忘了改文档，读者看到的就是错的契约。
 * 这里换成单向生成——schema 是唯一真相，文档是它的一个视图。
 * `packages/tools/test/docs.test.ts` 会在文档过期时**直接失败**，所以漂移不可能悄悄发生。
 *
 * 生成不出来的部分（坐标口径、`fill_line` 的半径语义这类只有散文能说清的东西）
 * 留在 `plan.md` 的附录里，文档开头指过去，而不是在这里再抄一遍。
 *
 * **两份，一种语言一份。** 工具描述本身是写给 LLM 的 prompt，所以永远是英文；
 * 可读的部分（标题、分组、表头、类型名）跟语言走。两份放两个文件而不是一份两段：
 * 正文占绝大多数篇幅，塞进一份里等于把同一段英文抄两遍。
 */
export type DocLocale = 'en-US' | 'zh-CN'

export const DOC_LOCALES: readonly DocLocale[] = ['en-US', 'zh-CN']

/** 每种语言的落盘路径（相对仓库根）。 */
export const DOC_PATHS: Record<DocLocale, string> = {
  'en-US': 'docs/tool-reference.md',
  'zh-CN': 'docs/tool-reference.zh-CN.md',
}

interface Scaffold {
  header: string
  batchTitle: string
  batchBlurb: string
  destructiveTitle: string
  destructiveBlurb: string
  inspectTitle: string
  inspectBlurb: string
  atAGlance: string
  tableHead: string
  tableRule: string
  other: string
  noArguments: string
  eachItem: (name: string) => string
  nestedHead: string
  nestedRule: string
  argHead: string
  argRule: string
  extraNote: string
  /** 类型名，键是 JSON Schema 的 `type`。 */
  types: Record<string, string>
  enumLabel: string
  arrayLabel: string
  arrayOfObjects: string
  items: (count: string) => string
  none: string
  join: string
}

const EN: Scaffold = {
  header: `<!-- Generated by packages/tools/src/docs.ts; do not edit by hand. -->
<!-- Regenerate: pnpm docs:gen -->

# Tool reference

> **This file is generated.** The single source of truth is each tool's own JSON Schema
> (\`packages/tools/src/tools/*.ts\`); change a schema and run \`pnpm docs:gen\` to regenerate.
> \`pnpm test\` fails while the document is stale.
>
> A parameter table can say which arguments exist; it cannot say why the semantics are what
> they are. That is in \`plan.md\`: **Appendix A** (the radius and taper semantics of
> \`fill_line\`), **Appendix C** (coordinate conventions for the geometry operators),
> **Appendix D** (transform and batch semantics), **Appendix E** (the traps in the export
> formats).
>
> Tool descriptions are prompts written for the LLM, so they are English in both files. This
> one is the English scaffolding; the Chinese one is \`tool-reference.zh-CN.md\`.
`,
  batchTitle: 'Batch editing',
  batchBlurb: 'Many cells in one call — **these are the workhorses**; placing block by block is the last resort.',
  destructiveTitle: 'Destructive editing',
  destructiveBlurb:
    'Deletes existing content. Past the confirmation threshold a call has to explain itself and be resent with `confirm: true`.',
  inspectTitle: 'Inspection (read-only, produces no revision)',
  inspectBlurb:
    "Reading back and locating. **Precise cell edits have to go through `slice`'s ASCII plan, never by counting pixels in a screenshot.**",
  atAGlance: '## At a glance',
  tableHead: '| Tool | Writes | Destructive | One line |',
  tableRule: '|------|:------:|:-----------:|----------|',
  other: '## Other',
  noArguments: '**No arguments.**',
  eachItem: (name) => `Each item of \`${name}[]\`:`,

  nestedHead: '| Field | Type | Required | Description |',
  nestedRule: '|-------|------|:--------:|-------------|',
  argHead: '| Argument | Type | Required | Values / range | Default | Description |',
  argRule: '|----------|------|:--------:|----------------|---------|-------------|',
  extraNote:
    '> This tool accepts **extra arguments validated by the inner tool itself** (see `additionalProperties: true`).',
  types: { integer: 'integer', number: 'number', boolean: 'boolean', object: 'object', string: 'string' },
  enumLabel: 'enum',
  arrayLabel: 'array',
  arrayOfObjects: 'array of objects',
  items: (count) => `${count} items`,
  none: '—',
  join: '; ',
}

const ZH: Scaffold = {
  header: `<!-- 由 packages/tools/src/docs.ts 生成，请勿手工编辑。 -->
<!-- 重新生成：pnpm docs:gen -->

# 工具参考

> **本文件是生成的。** 唯一真相是工具自己的 JSON Schema（\`packages/tools/src/tools/*.ts\`），
> 改 schema 之后跑 \`pnpm docs:gen\` 重新生成；文档过期时 \`pnpm test\` 会失败。
>
> 参数表能说清"有哪些参数"，说不清"这个语义为什么这样设计"。后者在 \`plan.md\` 里：
> **附录 A**（\`fill_line\` 的半径/锥度语义）、**附录 C**（几何算子的坐标口径）、
> **附录 D**（变换与批处理语义）、**附录 E**（导出格式的坑）。
>
> 工具描述本身是写给 LLM 的 prompt，所以两份里都是**英文**；这一份是中文件。
`,
  batchTitle: '批量编辑',
  batchBlurb: '一次调用改很多格——**这类工具是主力**，逐格摆放是最后手段。',
  destructiveTitle: '破坏性编辑',
  destructiveBlurb: '会删掉已有内容；触发确认阈值时需要先解释清楚再带 `confirm: true` 重发。',
  inspectTitle: '检视（只读，不产生 revision）',
  inspectBlurb: '读回与定位。**精确改格子必须靠 `slice` 的 ASCII 图，不能靠数截图里的像素。**',
  atAGlance: '## 一览',
  tableHead: '| 工具 | 改世界 | 破坏性 | 一句话 |',
  tableRule: '|------|:------:|:------:|--------|',
  other: '## 其他',
  noArguments: '**无参数。**',
  eachItem: (name) => `\`${name}[]\` 的每一项：`,
  nestedHead: '| 字段 | 类型 | 必填 | 说明 |',
  nestedRule: '|------|------|:----:|------|',
  argHead: '| 参数 | 类型 | 必填 | 取值 / 范围 | 默认 | 说明 |',
  argRule: '|------|------|:----:|-------------|------|------|',
  extraNote: '> 这个工具接受**额外的、由内层工具自己校验**的参数（见 `additionalProperties: true`）。',
  types: { integer: '整数', number: '数字', boolean: '布尔', object: '对象', string: '字符串' },
  enumLabel: '枚举',
  arrayLabel: '数组',
  arrayOfObjects: '对象数组',
  items: (count) => `${count} 项`,
  none: '—',
  join: '；',
}

const SCAFFOLDS: Record<DocLocale, Scaffold> = { 'en-US': EN, 'zh-CN': ZH }

export function renderToolReference(registry: ToolRegistry, locale: DocLocale = 'en-US'): string {
  const s = SCAFFOLDS[locale]
  const tools = registry.list()
  const lines: string[] = [s.header]

  lines.push(s.atAGlance + '\n')
  lines.push(s.tableHead)
  lines.push(s.tableRule)
  for (const tool of tools) {
    lines.push(
      `| [\`${tool.name}\`](#${anchor(tool.name)}) | ${tool.mutating ? '✅' : '—'} | ${
        tool.destructive ? '⚠️' : '—'
      } | ${firstSentence(tool.description)} |`,
    )
  }
  lines.push('')

  const groups: Array<{ title: string; blurb: string; match: (tool: ToolDefinition) => boolean }> = [
    {
      title: s.batchTitle,
      blurb: s.batchBlurb,
      match: (tool) => tool.mutating && !tool.destructive && tool.name !== 'undo' && tool.name !== 'redo',
    },
    { title: s.destructiveTitle, blurb: s.destructiveBlurb, match: (tool) => tool.mutating && tool.destructive },
    { title: s.inspectTitle, blurb: s.inspectBlurb, match: (tool) => !tool.mutating },
  ]

  const grouped = new Set<string>()
  for (const group of groups) {
    const members = tools.filter((tool) => group.match(tool) && !grouped.has(tool.name))
    if (members.length === 0) continue
    lines.push(`## ${group.title}\n`)
    lines.push(`${group.blurb}\n`)
    for (const tool of members) {
      grouped.add(tool.name)
      lines.push(...renderTool(tool, s))
    }
  }

  // 兜底：上面的分组条件如果漏掉了某个工具，也要出现在文档里而不是消失
  const ungrouped = tools.filter((tool) => !grouped.has(tool.name))
  if (ungrouped.length > 0) {
    lines.push(s.other + '\n')
    for (const tool of ungrouped) lines.push(...renderTool(tool, s))
  }

  return `${lines.join('\n').trimEnd()}\n`
}

/** 校验生成的文档是否与磁盘上的一致。返回不一致的原因（空数组表示一致）。 */
export function diffToolReference(registry: ToolRegistry, onDisk: string, locale: DocLocale = 'en-US'): string[] {
  const expected = renderToolReference(registry, locale)
  if (expected === onDisk) return []
  const expectedNames = [...expected.matchAll(/^## `([a-z_]+)`$/gm)].map((match) => match[1]!)
  const diskNames = [...onDisk.matchAll(/^## `([a-z_]+)`$/gm)].map((match) => match[1]!)
  const problems: string[] = []
  const missing = expectedNames.filter((name) => !diskNames.includes(name))
  const extra = diskNames.filter((name) => !expectedNames.includes(name))
  if (missing.length > 0) problems.push(`the document is missing: ${missing.join(', ')}`)
  if (extra.length > 0) problems.push(`the document lists tools that no longer exist: ${extra.join(', ')}`)
  if (problems.length === 0) problems.push('the document differs from the generated version (a description or argument changed?)')
  return problems
}

function renderTool(tool: ToolDefinition, s: Scaffold): string[] {
  const lines: string[] = [`## \`${tool.name}\`\n`]
  lines.push(`\`\`\`\n${tool.description}\n\`\`\`\n`)

  const schema = tool.parameters
  const required = new Set(schema.required ?? [])
  const properties = schema.properties ?? {}
  const entries = Object.entries(properties)

  if (entries.length === 0) {
    lines.push(s.noArguments + '\n')
    return lines
  }

  // 先收集行、再一次性输出：中间不能插空行，否则 Markdown 会把表格截成两半
  const rows: string[] = []
  const nested: string[] = []
  for (const [name, property] of entries) {
    rows.push(
      `| \`${name}\` | ${typeOf(property, s)} | ${required.has(name) ? '✅' : '—'} | ${constraintOf(property, s)} | ${
        property.default !== undefined ? `\`${JSON.stringify(property.default)}\`` : s.none
      } | ${oneLine(property.description ?? '')} |`,
    )
    // 数组元素的对象结构单独展开——`run_batch` 的 `ops[]` 就在这一层
    const itemProperties = property.items?.properties
    if (itemProperties === undefined || Object.keys(itemProperties).length === 0) continue
    const itemRequired = new Set(property.items?.required ?? [])
    nested.push(s.eachItem(name) + '\n')
    nested.push(s.nestedHead)
    nested.push(s.nestedRule)
    for (const [key, item] of Object.entries(itemProperties)) {
      nested.push(
        `| \`${key}\` | ${typeOf(item, s)} | ${itemRequired.has(key) ? '✅' : '—'} | ${oneLine(item.description ?? '')} |`,
      )
    }
    nested.push('')
  }

  lines.push(s.argHead)
  lines.push(s.argRule)
  lines.push(...rows)
  lines.push('')
  if (nested.length > 0) lines.push(...nested)
  if (schema.additionalProperties === true) {
    lines.push(s.extraNote)
    lines.push('')
  }
  return lines
}

function typeOf(schema: JsonSchema, s: Scaffold): string {
  if (schema.enum !== undefined) return s.enumLabel
  switch (schema.type) {
    case 'array': {
      if (schema.items === undefined) return s.arrayLabel
      return schema.items.type === 'object' ? s.arrayOfObjects : `${s.arrayLabel}<${typeOf(schema.items, s)}>`
    }
    case 'integer':
    case 'number':
    case 'boolean':
    case 'object':
    case 'string':
      return s.types[schema.type] ?? s.none
    default:
      return s.none
  }
}

function constraintOf(schema: JsonSchema, s: Scaffold): string {
  const parts: string[] = []
  if (schema.enum !== undefined) parts.push(schema.enum.map((value) => `\`${String(value)}\``).join(' / '))
  if (schema.type === 'integer' || schema.type === 'number') {
    if (schema.minimum !== undefined && schema.maximum !== undefined) parts.push(`${schema.minimum}..${schema.maximum}`)
    else if (schema.minimum !== undefined) parts.push(`≥ ${schema.minimum}`)
    else if (schema.maximum !== undefined) parts.push(`≤ ${schema.maximum}`)
  }
  if (schema.type === 'array') {
    if (schema.minItems !== undefined && schema.maxItems !== undefined) parts.push(s.items(`${schema.minItems}..${schema.maxItems}`))
    else if (schema.minItems !== undefined) parts.push(`≥ ${s.items(String(schema.minItems))}`)
    else if (schema.maxItems !== undefined) parts.push(`≤ ${s.items(String(schema.maxItems))}`)
  }
  return parts.length > 0 ? parts.join(s.join) : s.none
}

/** 表格单元格里不能有换行；描述常常是多行的。 */
const oneLine = (text: string): string => text.replace(/\s*\n\s*/g, ' ').trim()

/** 描述的第一句，用在一览表里。 */
function firstSentence(description: string): string {
  const flat = oneLine(description)
  const match = /^(.+?[.。])(?:\s|$)/.exec(flat)
  const sentence = match?.[1] ?? flat
  return sentence.length > 80 ? `${sentence.slice(0, 80)}…` : sentence
}

/** GitHub 风格的锚点。 */
function anchor(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9_-]/g, '')
}
